# Generated by Django 2.1.12 on 2019-09-21 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Rate')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Volume')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='stats.Currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Rate',
            },
        ),
    ]
