# Generated by Django 2.1.12 on 2019-09-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20190921_0831'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['-date', 'currency'], name='stats_index'),
        ),
    ]
